---
- hosts: all
  tasks:
    - name: run ansible galaxy
      local_action: command ansible-galaxy install -r requirements.yml --ignore-errors
    - include_vars:
        file: vars/main.yaml
    - include_role:
        name: "ansistrano.deploy"
