version: '3.1'

networks:
  api:
    driver: "bridge"
  frontend:
    driver: "bridge"

services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/sites:/etc/nginx/sites-enabled/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /certs/:/certs/:ro
    depends_on:
      - api
      - frontend
    networks:
      - api
      - frontend

  frontend:
    image: ghcr.io/statutis/frontend:main
    networks:
      - frontend

  api:
    image: ghcr.io/statutis/api:main
    environment:
      - ConnectionStrings__hostname=postgres
      - ConnectionStrings__username=admin
      - ConnectionStrings__password=your_secret_password
      - ConnectionStrings__database=statutis
      - JWT__secret={{ statutis_api_key }}
    depends_on:
      - postgres
    networks:
      - api

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=your_secret_password
      - POSTGRES_DB=statutis
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgress:/var/lib/postgresql/data
    networks:
      - api

volumes:
  postgress: