---
- name: Create shared files if not exists
  file:
    path: "{{ ansistrano_deploy_to }}/shared/nginx/sites"
    state: directory
    mode: 0755
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
- name: Create docker_compose
  template:
    src: docker-compose.yml
    dest: "{{ ansistrano_release_path.stdout }}/docker-compose.yml"
- name: Nginx | Create front vhost
  template:
    src: front.conf.j2
    dest: "{{ ansistrano_deploy_to }}/shared/nginx/sites/front.conf"
- name: Nginx | Create api vhost
  template:
    src: api.conf.j2
    dest: "{{ ansistrano_deploy_to }}/shared/nginx/sites/api.conf"
- name: Docker compose pull
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  shell:
    cmd: "docker-compose -p {{ project_name }} pull"